### ISSUE TITLE
Can not find "/android/legacy/org.apache.http.legacy.jar"

### ISSUE THREAD

**Issue by NmdOfficial** [ewpatton/appinventor-sources#6]
You have added to "appinventor/buildserver/build.xml"

in line 121 this:
< copy toFile="${classes.files.dir}/http-legacy.jar" file="${lib.dir}/android/legacy/org.apache.http.legacy.jar" />

Same for file:
appinventor/components/build.xml
in line 132.

But where is the lib for that?
![issue](https://user-images.githubusercontent.com/29900947/37756385-93acea78-2da9-11e8-87e4-0e77e7ec65cd.png)

I can not find the folder called "legacy" which is linked in both build.xml files.

**Comment by ewpatton** [comment]
@NmdOfficial I forgot to add that file before committing. The branch has been updated (see 6cb4294).
