### ISSUE TITLE
Target sdk >= 23 | New permission system required

### ISSUE THREAD

**Issue by michael-winkler** [ewpatton/appinventor-sources#9]
When we add target sdk >= 23 to the manifest we will get without doing any changes to the components big problems.

![1](https://user-images.githubusercontent.com/29900947/37952135-1760866a-319f-11e8-9f25-741bb5e6356c.png)

> https://github.com/ewpatton/appinventor-sources/blob/wip-target-sdk-26/appinventor/buildserver/src/com/google/appinventor/buildserver/Compiler.java#L658

If we set target sdk to as example >= 23, we have to show to the user on app start a dialog which request the needed app permissions.

This article explains really good what we have to do:
https://inthecheesefactory.com/blog/things-you-need-to-know-about-android-m-permission-developer-edition/en

And here is a link to a stackoverflow page:
https://stackoverflow.com/questions/34342816/android-6-0-multiple-permissions

More links to the android developer page:
https://developer.android.com/reference/android/support/v4/app/ActivityCompat.html#requestPermissions

https://developer.android.com/guide/topics/permissions/overview.html

**Comment by NmdOfficial** [comment]
@ewpatton Please look at this PR:
https://github.com/ewpatton/appinventor-sources/pull/8

I have added a runtime permission check.
I have testet it local too and the build apk works how it should.

![1](https://user-images.githubusercontent.com/29900947/38265669-d52041ae-3776-11e8-949f-9e315bd9db7a.png)
